tasks:
  - init: |
      echo "Gitpod init. Setting up peerjs-python dev environment."
      pip3 install -e ./src
    command: |
      pyenv global system
      echo "Started peerjs-python development environment."
      echo "To run the peerjs-python testsuite use:"
      echo "python3 -m pytest --cov=peerjs --cov-report=term tests/"
